version: '2'

services:
  mongo:
    restart: always
    image: mongo:3.2
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  mysql:
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    env_file:
        - variables.env

  memcached:
    restart: always
    image: memcached:1.4
    ports:
      - "11211:11211"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  app:
    build: docker/app
    restart: always
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application:/project
      - ./cache:/project/cache
      - ./logs:/project/logs
    depends_on:
      - mongo
      - mysql
      - redis
      - memcached
    env_file:
      - variables.env

volumes:
  mongo:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local
